runtime: nodejs18 # or another supported version

handlers:
  - url: /static
    static_dir: dist
  
  - url: /dynamic
    static_dir: tmp

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto